variables:
  DOCKERFILE: ${CI_PROJECT_DIR}/docker/web.Dockerfile
  RELEASE_REGISTRY: docker.io
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-naldo
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

include:
  - project: "labs/salt-automation"
    ref: "master"
    file: "/gitlab-ci-templates/common/conventional-commits.v1.yml"
  - project: "labs/salt-automation"
    ref: "master"
    file: "/gitlab-ci-templates/common/docker-build.v1.yml"
  - project: "labs/salt-automation"
    ref: "master"
    file: "/gitlab-ci-templates/common/docker-release.v1.yml"
  - project: "labs/salt-automation"
    file: "gitlab-ci-templates/common/config-updater-meta.v1.yml"

stages: 
  - lint
  - build
  - release
  - deploy

Pre-commit:
  image: python:3.9
  stage: lint
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

Pages:
  image: node:latest
  stage: deploy
  script:
    - cd web/
    - yarn
    - yarn build
    - cp -r build/ ../public
  artifacts:
    paths:
      - public
  # only:
  #   - master

Deploy to dev:
  extends: .release-to-dev
  needs:
    - Release version
  variables:
    ENDPOINT: os2mo/flux/naldo/update-dev

Deploy to test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/flux/naldo/update-test

Deploy to prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/flux/naldo/update-prod
