repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: \.(ts|js|svelte|css|html)$
        exclude: types\.ts$|query\.generated\.ts$
        args: [--config, web/.prettierrc, --plugin-search-dir=./web, --write]
        additional_dependencies:
          - prettier@2.8.8
          - prettier-plugin-svelte@2.10.1
          - prettier-plugin-organize-imports@3.2.4
          - svelte@4.2.8

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
