version: "3.7"

services:
  web:
    image: web
    restart: on-failure
    build:
      context: ./web
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
